In [1]:
import pandas as pd

En este punto cargamos el archivo cvs para la exploración de datos.

In [2]:
df = pd.read_csv("HURTO_A_VEH_CULOS_20250409.csv")

con head y el número dentro de los parentesis nos trae la cantidad de registros que queremos visualizar.

In [6]:
df.head(4)

,FECHA HECHO,COD_DEPTO,DEPARTAMENTO,COD_MUNI,MUNICIPIO,TIPO DELITO,ZONA,CANTIDAD
0,01/01/2003,91,AMAZONAS,91001,LETICIA,HURTO A MOTOCICLETAS,URBANA,1
1,01/01/2003,5,ANTIOQUIA,5088,BELLO,HURTO AUTOMOTORES,URBANA,1
2,01/01/2003,5,ANTIOQUIA,5001,MEDELLIN,HURTO A MOTOCICLETAS,URBANA,5
3,01/01/2003,85,CASANARE,85001,YOPAL,HURTO A MOTOCICLETAS,URBANA,1

In [ ]:
con tail y el número dentro de los parentesis nos trae la cantidad de registros 
que queremos visualizar y que se encuentra al final de nuestra base.

In [7]:
df.tail(4)

,FECHA HECHO,COD_DEPTO,DEPARTAMENTO,COD_MUNI,MUNICIPIO,TIPO DELITO,ZONA,CANTIDAD
356034,28/02/2025,76,VALLE DEL CAUCA,76130,CANDELARIA,HURTO A MOTOCICLETAS,URBANA,1
356035,28/02/2025,76,VALLE DEL CAUCA,76364,JAMUNDI,HURTO AUTOMOTORES,URBANA,1
356036,28/02/2025,76,VALLE DEL CAUCA,76520,PALMIRA,HURTO AUTOMOTORES,URBANA,1
356037,28/02/2025,76,VALLE DEL CAUCA,76520,PALMIRA,HURTO A MOTOCICLETAS,URBANA,3

In [ ]:
con Df.info nos deja visualizar el total de filas, el nombre de las columnas, el tipo de datos.

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 356038 entries, 0 to 356037
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   FECHA HECHO   356038 non-null  str
 1   COD_DEPTO     356038 non-null  int64
 2   DEPARTAMENTO  356038 non-null  str
 3   COD_MUNI      356038 non-null  int64
 4   MUNICIPIO     356038 non-null  str
 5   TIPO DELITO   356038 non-null  str
 6   ZONA          356038 non-null  str
 7   CANTIDAD      356038 non-null  int64
dtypes: int64(3), str(5)
memory usage: 21.7 MB

Con df.describe me permite validar datos estadisticos como la cantidad de registros, el promedio, la mediana,el maximo, minimo

In [10]:
df.describe()

           COD_DEPTO       COD_MUNI       CANTIDAD
count  356038.000000  356038.000000  356038.000000
mean       37.793845   38037.348011       2.081621
std        27.269614   27268.549950       2.786445
min         5.000000    5001.000000       1.000000
25%        11.000000   11001.000000       1.000000
50%        27.000000   27001.000000       1.000000
75%        66.000000   66400.000000       2.000000
max        99.000000   99773.000000      46.000000

Preguntas de analisis de datos.
1. Los 5 Municipio donde se registra una cantidad maxima de hurtos.
2. Cantidad de hurtos por departamento.
3. Tipo de delito mas común.

In [ ]:
Para encontrar los 5 municipios con mayor numero de hurtos, dejamos la funcion 
value al final del data frame para que me cuente la cantidad por cada item registrado.

In [21]:
hurtos_municipio = df["MUNICIPIO"].value_counts()
hurtos_municipio.head(5)

MUNICIPIO
CALI            17146
MEDELLIN        16157
BOGOTA D.C.     16138
BARRANQUILLA    11471
POPAYAN          8823
Name: count, dtype: int64

Para hallar la cantidad de hurtos utilizamos una agrupaciòn de información.

In [18]:
df.groupby("DEPARTAMENTO").size()

DEPARTAMENTO
AMAZONAS                514
ANTIOQUIA             54327
ARAUCA                 2865
ATLANTICO             22387
BOGOTA D.C.           16138
BOLIVAR               10648
BOYACA                 3137
CALDAS                 3531
CAQUETA                4345
CASANARE               4846
CAUCA                 25402
CESAR                 13804
CHOCO                  3185
CORDOBA                7057
CUNDINAMARCA          14458
GUAINIA                  60
GUAVIARE                605
HUILA                 17482
LA GUAJIRA            10550
MAGDALENA              8320
META                  12082
NARIÑO                15549
NORTE DE SANTANDER    13799
PUTUMAYO               3223
QUINDIO                3856
RISARALDA              7579
SAN ANDRES ISLAS       1033
SANTANDER             15546
SUCRE                  5425
TOLIMA                 9845
VALLE DEL CAUCA       44101
VAUPES                   39
VICHADA                 300
dtype: int64

Para hallar el tipo de delito mas com+un utilizamos el data frame filtrando la columna tipo de delito y contando la cantidad por cada registro encontrado, para lo cual nos muestra que el tipo de delito mas comun es motocicletas seguido de automotores.

In [19]:
df["TIPO DELITO"].value_counts()

TIPO DELITO
HURTO A MOTOCICLETAS    266162
HURTO AUTOMOTORES        89876
Name: count, dtype: int64